language: csharp
mono: none
dotnet: 5.0
services:
  - docker

script:
  - echo "test script"

deploy:
  skip_cleanup: true
  provider: script
  script: bash travis/deploy.sh
  on:
      branch: master